# Generated by Django 4.2.3 on 2023-07-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_size_remove_product_size_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', (('USD', 'USD'), ('$', '$')))], max_length=30, null=True),
        ),
    ]
