# Generated by Django 4.2.3 on 2023-07-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
    ]
