# Generated by Django 4.2.3 on 2023-07-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ManyToManyField(to='product.currency'),
        ),
    ]
