# Generated by Django 4.2.3 on 2023-07-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_currency_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('JPY', '¥'), ('GBP', '£')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
